require:
  - rubocop-packaging
  - rubocop-rails
AllCops:
  NewCops: disable
  TargetRubyVersion: 2.6
  Exclude:
    - 'gemfiles/*'
Bundler/OrderedGems:
  Include:
    - '**/Gemfile'
Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation
Layout/CommentIndentation:
  Enabled: false
Layout/ConditionPosition:
  Enabled: false
Layout/DotPosition:
  EnforcedStyle: trailing
Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true
Layout/HeredocIndentation:
  Enabled: false
Layout/LineLength:
  Exclude:
    - spec/**/*
  IgnoredPatterns:
    - !ruby/regexp /\A +(it|describe|context|shared_examples|include_examples|it_behaves_like) ["']/
    - !ruby/regexp /\A(require|require_relative) ["']/
    - '^[ ]*#.+$'
    - '^[ ]*''.+?'' => ''.+?'',?$'
    - '^[ ]*".+?" => ".+?",?$'
  Max: 80
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation
Layout/SpaceInLambdaLiteral:
  EnforcedStyle: require_space
Layout/SpaceInsideBlockBraces:
  Enabled: false
Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*
Lint/AmbiguousOperator:
  Enabled: false
Lint/AmbiguousRegexpLiteral:
  Enabled: false
Lint/AssignmentInCondition:
  Enabled: false
Lint/DeprecatedClassMethods:
  Enabled: false
Lint/ElseLayout:
  Enabled: false
Lint/FlipFlop:
  Enabled: false
Lint/LiteralInInterpolation:
  Enabled: false
Lint/Loop:
  Enabled: false
Lint/MissingSuper:
  Enabled: false
Lint/ParenthesesAsGroupedExpression:
  Enabled: false
Lint/RequireParentheses:
  Enabled: false
Lint/SafeNavigationChain:
  Enabled: false
Lint/SuppressedException:
  Enabled: false
Lint/UnderscorePrefixedVariableName:
  Enabled: false
Lint/Void:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Max: 30
Metrics/ModuleLength:
  Enabled: true
  Exclude:
    - spec/**/*
Metrics/ParameterLists:
  CountKeywordArgs: false
Metrics/PerceivedComplexity:
  Enabled: false
Naming/AccessorMethodName:
  Enabled: false
Naming/AsciiIdentifiers:
  Enabled: false
Naming/BinaryOperatorParameterName:
  Enabled: false
Naming/FileName:
  Enabled: false
Naming/HeredocDelimiterNaming:
  Enabled: false
Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: required
Naming/PredicateName:
  Enabled: false
Naming/RescuedExceptionsVariableName:
  Enabled: false
Rails/Date:
  Enabled: false
Rails/Delegate:
  Enabled: false
Rails/HttpPositionalArguments:
  Enabled: false
Rails/SkipsModelValidations:
  Exclude:
    - spec/**/*
Rails/TimeZone:
  Enabled: false
Style/Alias:
  Enabled: false
Style/ArrayJoin:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/Attr:
  Enabled: false
Style/BlockDelimiters:
  Enabled: false
Style/CaseEquality:
  Enabled: false
Style/CharacterLiteral:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/ClassVars:
  Enabled: false
Style/CollectionMethods:
  Enabled: true
  PreferredMethods:
    collect: map
    find: detect
    find_all: select
    reduce: inject
Style/ColonMethodCall:
  Enabled: false
Style/CommentAnnotation:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Style/EachWithObject:
  Enabled: false
Style/EmptyElse:
  Enabled: false
Style/EmptyLiteral:
  Enabled: false
Style/EmptyMethod:
  EnforcedStyle: expanded
Style/Encoding:
  Enabled: false
Style/EvenOdd:
  Enabled: false
Style/FormatString:
  Enabled: false
Style/FormatStringToken:
  EnforcedStyle: template
Style/FrozenStringLiteralComment:
  Enabled: false
Style/GlobalVars:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/IfWithSemicolon:
  Enabled: false
Style/InlineComment:
  Enabled: false
Style/InverseMethods:
  Enabled: false
Style/Lambda:
  Enabled: false
Style/LambdaCall:
  Enabled: false
Style/LineEndConcatenation:
  Enabled: false
Style/MethodCalledOnDoEndBlock:
  Enabled: false
Style/ModuleFunction:
  Enabled: false
Style/NegatedIf:
  Enabled: false
Style/NegatedWhile:
  Enabled: false
Style/Next:
  Enabled: false
Style/NilComparison:
  Enabled: false
Style/Not:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/OneLineConditional:
  Enabled: false
Style/OptionalBooleanParameter:
  Enabled: false
Style/ParenthesesAroundCondition:
  Enabled: false
Style/PercentLiteralDelimiters:
  Enabled: false
Style/PerlBackrefs:
  Enabled: false
Style/PreferredHashMethods:
  Enabled: false
Style/Proc:
  Enabled: false
Style/RaiseArgs:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
Style/SelfAssignment:
  Enabled: false
Style/SignalException:
  Enabled: false
Style/SingleLineBlockParams:
  Enabled: false
Style/SingleLineMethods:
  Enabled: false
Style/SpecialGlobalVars:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: single_quotes
Style/SymbolArray:
  Enabled: false
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrivialAccessors:
  Enabled: false
Style/VariableInterpolation:
  Enabled: false
Style/WhenThen:
  Enabled: false
Style/WhileUntilModifier:
  Enabled: false
Style/WordArray:
  Enabled: false
