#!/usr/bin/env ruby
# frozen_string_literal: true

require 'yaml'

travis_config_path = File.expand_path('../../.travis.yml', __FILE__)
travis_config = YAML.load_file(travis_config_path)
puts travis_config.fetch('rvm').join(' ')
