#!/bin/bash

set -euo pipefail

SUPPORTED_VERSIONS=$(script/supported_ruby_versions)

update-gems-for-version() {
  local version="$1"
  (export RBENV_VERSION=$version; bundle update "${@:2}"; bundle exec appraisal update "${@:2}")
}

for version in $SUPPORTED_VERSIONS; do
  echo
  echo "*** Updating gems for $version ***"
  update-gems-for-version "$version" "$@"
done
